### ISSUE TITLE
Problems with fetch_add for T*

### ISSUE THREAD

**Issue by mrzv** [avakar/atomic_ref#1] opened 2020-03-10 16:20 UTC
When I try to compile the tests, I get the following error:
```
[ 50%] Building CXX object CMakeFiles/avakar_atomic_ref_test.dir/test/test.cpp.o
In file included from .../atomic_ref/test/test.cpp:1:
.../atomic_ref/include/avakar/atomic_ref.h: In instantiation of ‘T* avakar::_atomic_ref<T*>::fetch_add(avakar::_atomic_ref<T*>::difference_type, std::memory_order) const [with T = long unsigned int; avakar::_atomic_ref<T*>::value_type = long unsigned int*; avakar::_atomic_ref<T*>::difference_type = long int; std::memory_order = std::memory_order]’:
.../atomic_ref/test/test.cpp:14:29:   required from here
.../atomic_ref/include/avakar/atomic_ref.h:217:40: error: no matching function for call to ‘fetch_add(long unsigned int*&, avakar::_atomic_ref<long unsigned int*, void>::difference_type&, std::memory_order&)’
  217 |   return _avakar::atomic_ref::fetch_add(_obj, arg, order);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from .../atomic_ref/include/avakar/atomic_ref.h:12,
                 from .../atomic_ref/test/test.cpp:1:
.../atomic_ref/include/avakar/../../src/atomic_ref.gcc.h:59:3: note: candidate: ‘template<class T> T _avakar::atomic_ref::fetch_add(T&, T, std::memory_order)’
   59 | T fetch_add(T & obj, T arg, std::memory_order order) noexcept
      |   ^~~~~~~~~
.../atomic_ref/include/avakar/../../src/atomic_ref.gcc.h:59:3: note:   template argument deduction/substitution failed:
In file included from .../atomic_ref/test/test.cpp:1:
.../atomic_ref/include/avakar/atomic_ref.h:217:40: note:   deduced conflicting types for parameter ‘T’ (‘long unsigned int*’ and ‘long int’)
  217 |   return _avakar::atomic_ref::fetch_add(_obj, arg, order);
```

As far as I can tell, the complaint is justified. When using `atomic_ref<T*>::fetch_add()`,  there is no suitable specialization in `atomic_ref.gcc.h`: `fetch_add` gets `T = long unsigend*`, so `obj` is `long unsigned *&`, which is fine, but the arg with `long unsigned*` doesn't make sense, since it's just an integer `difference_type` in the caller.

**Comment by avakar** [comment] 2020-03-13 05:12
Thanks for the report! The issue is fixed in master and I've also added an automatic build so that this doesn't happen again.

**Closed as completed by avakar** 2020-03-13 05:12 UTC
Labels: bug

**Comment by mrzv** [comment] 2020-03-13 15:48
I don't believe your fix is sufficient. GCC's `__atomic_fetch_add`, when applied to the pointer, doesn't account for the size of `T`, so you need to multiply your operand explicitly by it.

Search for `uintptr_t` on the [page about __atomic builtins](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html).
